In [80]:
import numpy as np
import pandas as pd

df = pd.read_csv('matches.csv')
#df.head()
#df.info()
#df.describe()
#df['city'].unique()

In [12]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [15]:
df.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [16]:
df['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [20]:
df['player_of_match'].value_counts()

player_of_match
AB de Villiers       25
CH Gayle             22
RG Sharma            19
DA Warner            18
V Kohli              18
                     ..
NV Ojha               1
KV Sharma             1
Washington Sundar     1
PD Collingwood        1
Shahbaz Ahmed         1
Name: count, Length: 291, dtype: int64

In [21]:
df['toss_winner'].value_counts()

toss_winner
Mumbai Indians                 143
Kolkata Knight Riders          122
Chennai Super Kings            122
Rajasthan Royals               120
Royal Challengers Bangalore    113
Sunrisers Hyderabad             88
Kings XI Punjab                 85
Delhi Daredevils                80
Delhi Capitals                  50
Deccan Chargers                 43
Punjab Kings                    24
Gujarat Titans                  22
Pune Warriors                   20
Lucknow Super Giants            19
Gujarat Lions                   15
Kochi Tuskers Kerala             8
Royal Challengers Bengaluru      8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: count, dtype: int64

In [78]:
df[df['target_runs']>=250]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
352,598027,2013,Bangalore,2013-04-23,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,Royal Challengers Bangalore,runs,130.0,264.0,20.0,yes,NaN,Aleem Dar,C Shamshuddin
987,1359512,2023,Chandigarh,2023-04-28,League,MP Stoinis,"Punjab Cricket Association IS Bindra Stadium, ...",Lucknow Super Giants,Punjab Kings,Punjab Kings,field,Lucknow Super Giants,runs,56.0,258.0,20.0,yes,NaN,Nitin Menon,Vinod Seshan
1031,1422126,2024,Hyderabad,2024-03-27,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Sunrisers Hyderabad,runs,31.0,278.0,20.0,yes,NaN,KN Ananthapadmanabhan,UV Gandhe
1039,1422134,2024,Visakhapatnam,2024-04-03,League,SP Narine,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,106.0,273.0,20.0,yes,NaN,A Totre,UV Gandhe
1053,1426268,2024,Bengaluru,2024-04-15,League,TM Head,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,runs,25.0,288.0,20.0,yes,NaN,AK Chaudhary,R Pandit
1058,1426273,2024,Delhi,2024-04-20,League,TM Head,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,67.0,267.0,20.0,yes,NaN,J Madanagopal,Navdeep Singh
1065,1426280,2024,Kolkata,2024-04-26,League,JM Bairstow,"Eden Gardens, Kolkata",Kolkata Knight Riders,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,8.0,262.0,20.0,yes,NaN,AK Chaudhary,YC Barde
1066,1426281,2024,Delhi,2024-04-27,League,J Fraser-McGurk,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Delhi Capitals,runs,10.0,258.0,20.0,yes,NaN,Navdeep Singh,NA Patwardhan

In [94]:
print(df[df['super_over'] == 'Y'])

          id   season       city        date match_type player_of_match  \
66    392190     2009  Cape Town  2009-04-23     League       YK Pathan
130   419121  2009/10    Chennai  2010-03-21     League        J Theron
328   598004     2013  Hyderabad  2013-04-07     League       GH Vihari
342   598017     2013  Bangalore  2013-04-16     League         V Kohli
416   729315     2014  Abu Dhabi  2014-04-29     League     JP Faulkner
475   829741     2015  Ahmedabad  2015-04-21     League        SE Marsh
610  1082625     2017     Rajkot  2017-04-29     League       KH Pandya
705  1175365     2019      Delhi  2019-03-30     League         PP Shaw
746  1178426     2019     Mumbai  2019-05-02     League       JJ Bumrah
757  1216493  2020/21        NaN  2020-09-20     League      MP Stoinis
765  1216547  2020/21        NaN  2020-09-28     League  AB de Villiers
790  1216512  2020/21  Abu Dhabi  2020-10-18     League     LH Ferguson
791  1216517  2020/21        NaN  2020-10-18     League        KL Rahul
835  1254077     2021    Chennai  2021-04-25     League         PP Shaw

                                         venue                        team1  \
66                                    Newlands        Kolkata Knight Riders
130            MA Chidambaram Stadium, Chepauk          Chennai Super Kings
328  Rajiv Gandhi International Stadium, Uppal          Sunrisers Hyderabad
342                      M Chinnaswamy Stadium  Royal Challengers Bangalore
416                       Sheikh Zayed Stadium        Kolkata Knight Riders
475               Sardar Patel Stadium, Motera             Rajasthan Royals
610     Saurashtra Cricket Association Stadium                Gujarat Lions
705                       Arun Jaitley Stadium        Kolkata Knight Riders
746                           Wankhede Stadium               Mumbai Indians
757        Dubai International Cricket Stadium               Delhi Capitals
765        Dubai International Cricket Stadium  Royal Challengers Bangalore
790                       Sheikh Zayed Stadium        Kolkata Knight Riders
791        Dubai International Cricket Stadium               Mumbai Indians
835   MA Chidambaram Stadium, Chepauk, Chennai               Delhi Capitals

                           team2                  toss_winner toss_decision  \
66              Rajasthan Royals        Kolkata Knight Riders         field
130              Kings XI Punjab          Chennai Super Kings         field
328  Royal Challengers Bangalore  Royal Challengers Bangalore           bat
342             Delhi Daredevils  Royal Challengers Bangalore         field
416             Rajasthan Royals             Rajasthan Royals           bat
475              Kings XI Punjab              Kings XI Punjab         field
610               Mumbai Indians                Gujarat Lions           bat
705               Delhi Capitals               Delhi Capitals         field
746          Sunrisers Hyderabad               Mumbai Indians           bat
757              Kings XI Punjab              Kings XI Punjab         field
765               Mumbai Indians               Mumbai Indians         field
790          Sunrisers Hyderabad          Sunrisers Hyderabad         field
791              Kings XI Punjab               Mumbai Indians           bat
835          Sunrisers Hyderabad               Delhi Capitals           bat

                          winner result  result_margin  target_runs  \
66              Rajasthan Royals    tie            NaN        151.0
130              Kings XI Punjab    tie            NaN        137.0
328          Sunrisers Hyderabad    tie            NaN        131.0
342  Royal Challengers Bangalore    tie            NaN        153.0
416             Rajasthan Royals    tie            NaN        153.0
475              Kings XI Punjab    tie            NaN        192.0
610               Mumbai Indians    tie            NaN        154.0
705               Delhi Capitals    tie            NaN        186.0
746               Mumbai Indians    tie            NaN        163.0
757               Delhi Capitals    tie            NaN        158.0
765  Royal Challengers Bangalore    tie            NaN        202.0
790        Kolkata Knight Riders    tie            NaN        164.0
791              Kings XI Punjab    tie            NaN        177.0
835               Delhi Capitals    tie            NaN        160.0

     target_overs super_over method       umpire1                umpire2
66           20.0          Y    NaN     MR Benson              M Erasmus
130          20.0          Y    NaN   K Hariharan              DJ Harper
328          20.0          Y    NaN  AK Chaudhary                 S Ravi
342          20.0          Y    NaN     M Erasmus            VA Kulkarni
416          20.0          Y    NaN     Aleem Dar           AK Chaudhary
475          20.0          Y    NaN     M Erasmus                 S Ravi
610          20.0          Y    NaN  AK Chaudhary            CB Gaffaney
705          20.0          Y    NaN   AY Dandekar            Nitin Menon
746          20.0          Y    NaN     CK Nandan                 S Ravi
757          20.0          Y    NaN  AK Chaudhary            Nitin Menon
765          20.0          Y    NaN   Nitin Menon             PR Reiffel
790          20.0          Y    NaN     PG Pathak                 S Ravi
791          20.0          Y    NaN   Nitin Menon             PR Reiffel
835          20.0          Y    NaN   CB Gaffaney  KN Ananthapadmanabhan

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [96]:
df.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [101]:
df['result_margin'].sort_values(ascending=False).head(10)

620     146.0
560     144.0
0       140.0
496     138.0
352     130.0
706     118.0
1009    112.0
236     111.0
1039    106.0
55      105.0
Name: result_margin, dtype: float64

In [103]:
df['city'].value_counts()

city
Mumbai            173
Kolkata            93
Delhi              90
Chennai            85
Hyderabad          77
Bangalore          65
Chandigarh         61
Jaipur             57
Pune               51
Abu Dhabi          37
Ahmedabad          36
Bengaluru          29
Durban             15
Visakhapatnam      15
Lucknow            14
Dubai              13
Dharamsala         13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Navi Mumbai         9
Johannesburg        8
Cuttack             7
Port Elizabeth      7
Ranchi              7
Cape Town           7
Raipur              6
Mohali              5
Kochi               5
Kanpur              4
Kimberley           3
East London         3
Guwahati            3
Nagpur              3
Bloemfontein        2
Name: count, dtype: int64